<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="MeltySynth" />
    <Content Include="../assets/sf_spec_test.sf2" Link="sf_spec_test.sf2" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../../src/Tessitura.Core/Tessitura.Core.csproj" />
    <ProjectReference Include="../../src/Tessitura.Playback/Tessitura.Playback.csproj" />
  </ItemGroup>
</Project>
