<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="MeltySynth" />
    <PackageReference Include="Melanchall.DryWetMidi" />
    <PackageReference Include="Silk.NET.OpenAL" />
    <PackageReference Include="Silk.NET.OpenAL.Soft.Native" />
    <PackageReference Include="JAJ.Packages.MiniAudioEx" />
    <PackageReference Include="SkiaSharp" />
    <Content Include="../assets/sf_spec_test.sf2" Link="sf_spec_test.sf2" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../../src/Tessitura.Playback/Tessitura.Playback.csproj" />
    <ProjectReference Include="../../src/Tessitura.Engraving/Tessitura.Engraving.csproj" />
    <ProjectReference Include="../../src/Tessitura.Rendering/Tessitura.Rendering.csproj" />
  </ItemGroup>
</Project>
