<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../src/Tessitura.Engraving/Tessitura.Engraving.csproj" />
    <ProjectReference Include="../../src/Tessitura.Smufl/Tessitura.Smufl.csproj" />
  </ItemGroup>
</Project>
