<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Tessitura.Core/Tessitura.Core.csproj" />
    <ProjectReference Include="../Tessitura.Editing/Tessitura.Editing.csproj" />
    <ProjectReference Include="../Tessitura.Engraving/Tessitura.Engraving.csproj" />
  </ItemGroup>
</Project>
