<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Tessitura.Engraving/Tessitura.Engraving.csproj" />
    <ProjectReference Include="../Tessitura.Smufl/Tessitura.Smufl.csproj" />
  </ItemGroup>
</Project>
