<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../src/Tessitura.Core/Tessitura.Core.csproj" />
    <ProjectReference Include="../../src/Tessitura.Editing/Tessitura.Editing.csproj" />
  </ItemGroup>
</Project>
